import pandas as pd

print("1. Epa Vehicle Fuel Economy Data")
epa_df = pd.read_csv('data/raw/vehicles.csv', low_memory=False)
print(f"\nShape: {epa_df.shape[0]} rows, {epa_df.shape[1]} columns")
print(f"\nColumn names:\n{list(epa_df.columns)}")
#print(f"\nFirst 5 rows:")
#print(epa_df.head(5))
print(f"\nData types:\n{epa_df.dtypes}")

print("\n2. NHTSA Vehicle Complaints Data")
nhtsa_df = pd.read_csv('data/raw/COMPLAINTS_RECEIVED_2020-2024.txt', sep='\t', low_memory=False)
print(f"\nShape: {nhtsa_df.shape[0]} rows, {nhtsa_df.shape[1]} columns")
print(f"\nColumn names:\n{list(nhtsa_df.columns)}")
print(f"\nFirst 5 rows:")
#print(nhtsa_df.head(5))
#print(f"\nData types:\n{nhtsa_df.dtypes}")

print("3. DOE Alternative Fuel Stations Data")
doe_df = pd.read_csv('data/raw/alt_fuel_stations.csv', low_memory=False)
print(f"\nShape: {doe_df.shape[0]} rows, {doe_df.shape[1]} columns")
print(f"\nColumn names:\n{list(doe_df.columns)}")
#print(f"\nFirst 5 rows:")
#print(doe_df.head(5))
print(f"\nData types:\n{doe_df.dtypes}")

print("Summary")
print(f"EPA Vehicles: {epa_df.shape[0]:,} records")
print(f"NHTSA Complaints: {nhtsa_df.shape[0]:,} records")
print(f"DOE Fuel Stations: {doe_df.shape[0]:,} records")
print(f"\nTotal records across all datasets: {epa_df.shape[0] + nhtsa_df.shape[0] + doe_df.shape[0]:,}")